### ISSUE TITLE
Some NFT queries use `firstVerifiedCreators` instead of `firstVerifiedCreator`

### ISSUE THREAD

**Issue by ltirrell** [vmpyre/helius_sdk#1]
At times the `firstVerifiedCreator` key is pluralized to `firstVerifiedCreators`, other times it is not.

For example, this line needs to be switched to `firstVerifiedCreators`
https://github.com/vmpyre/helius_sdk/blob/master/src/helius/nft.py#L62

Currently `NFTAPI().get_mintlists` returns a ValueError:
```
ValueError: Error: 400: b'{"error":"invalid request payload: unknown field \'firstVerifiedCreator\'"}'
```

**Comment by vmpyre** [comment]
Thanks for pointing this out. Issue should be resolved in the new commit and also in v0.0.2 on pip.
